import { consola } from "consola";
import { parse } from "maml.js";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Per-repo envi config filename.
 *
 * No leading dot — meant to be visible and committed alongside source code.
 * Holds an optional `encryption_key`, an optional `capture_patterns` list, and
 * any future per-repo configuration.
 */
export const KEY_FILE_NAME = "envi.config.maml";

/**
 * Legacy filename for the per-repo envi config.
 *
 * Kept readable so already-committed files continue to work. New files use
 * `KEY_FILE_NAME`. When a write targets a repo that only has the legacy file,
 * the legacy file is edited in place rather than silently migrating it — the
 * user decides when to rename and commit.
 */
export const LEGACY_KEY_FILE_NAME = "envi.maml";

/** MAML key under which the encryption key is stored */
const ENCRYPTION_KEY_FIELD = "encryption_key";

/** MAML key under which extra capture file patterns are stored */
const CAPTURE_PATTERNS_FIELD = "capture_patterns";

const COMMENT_BLOCK = [
  "# Generated by `envi create-key`. Team-shared encryption key meant to be",
  "# committed. Convenience, not security: gives `envi pack` / `envi unpack`",
  "# a stable key that survives manifest changes (so shared blobs don't",
  "# break after `pnpm install`), and encrypts `~/.envi/store/` — mainly",
  "# useful with the GitHub backup (`envi global github enable`).",
  "#",
  "# Anyone with repo access can decrypt, so this repo should be private.",
  "# On a public repo this gives no confidentiality; use a custom secret",
  "# with `envi pack` instead.",
  "#",
  "# See: https://envi.codecompose.dev/commands/create-key",
];

/**
 * Track repo roots for which we already nudged the user about the legacy
 * filename, so capture/restore/unpack don't each emit the same hint in a single
 * session.
 */
const legacyHintShown = new Set<string>();

function emitLegacyHintOnce(repoRoot: string): void {
  if (legacyHintShown.has(repoRoot)) return;
  legacyHintShown.add(repoRoot);
  consola.info(
    `Found legacy ${LEGACY_KEY_FILE_NAME} — consider renaming to ${KEY_FILE_NAME}.`,
  );
}

/**
 * Locate the existing per-repo config file, preferring the canonical name.
 *
 * Returns null when neither file exists. The `isLegacy` flag lets callers
 * surface a deprecation hint without re-checking the filename.
 */
function findExistingKeyFile(
  repoRoot: string,
): { path: string; isLegacy: boolean } | null {
  const canonical = join(repoRoot, KEY_FILE_NAME);
  if (existsSync(canonical)) {
    return { path: canonical, isLegacy: false };
  }
  const legacy = join(repoRoot, LEGACY_KEY_FILE_NAME);
  if (existsSync(legacy)) {
    return { path: legacy, isLegacy: true };
  }
  return null;
}

/**
 * Get the absolute path to the canonical envi config file in a repository.
 *
 * Always returns the canonical path, even if only the legacy file is on disk —
 * this is the path new files are written to.
 */
export function getKeyFilePath(repoRoot: string): string {
  return join(repoRoot, KEY_FILE_NAME);
}

/**
 * Check whether a per-repo envi config file exists, including the legacy name.
 *
 * Note: this does not check whether `encryption_key` is set inside it; use
 * `readEncryptionKey` for that.
 */
export function hasKeyFile(repoRoot: string): boolean {
  return findExistingKeyFile(repoRoot) !== null;
}

/**
 * Parse the per-repo config file, preferring the canonical name and falling
 * back to the legacy name. Emits a one-time hint per repo when the legacy file
 * is the one that was read. Returns null on missing or malformed files.
 */
function readConfig(repoRoot: string): Record<string, unknown> | null {
  const found = findExistingKeyFile(repoRoot);
  if (!found) return null;
  if (found.isLegacy) {
    emitLegacyHintOnce(repoRoot);
  }
  try {
    const content = readFileSync(found.path, "utf-8");
    const parsed = parse(content) as Record<string, unknown> | null;
    if (parsed && typeof parsed === "object") {
      return parsed;
    }
  } catch {
    /** Treat malformed file as "no config" — caller surfaces a clearer error */
  }
  return null;
}

/**
 * Read the encryption key from the per-repo config file, if present.
 *
 * Reads from `envi.config.maml` (preferred) or the legacy `envi.maml`. Returns
 * null when no config file is present, the file can't be parsed, or no
 * `encryption_key` field is set.
 */
export function readEncryptionKey(repoRoot: string): string | null {
  const parsed = readConfig(repoRoot);
  if (!parsed) return null;
  const value = parsed[ENCRYPTION_KEY_FIELD];
  if (typeof value === "string" && value.length > 0) {
    return value;
  }
  return null;
}

/**
 * Read additional capture patterns the user has declared for this repo.
 *
 * Patterns are merged with the built-in defaults inside `findEnvFiles` —
 * unknown filenames (e.g. `.envrc`, framework-specific secret files) become
 * captureable without code changes. Returns an empty array when the field is
 * missing, malformed, or not an array. Non-string entries are filtered out so
 * a partly-malformed list does not poison the whole capture.
 */
export function readCapturePatterns(repoRoot: string): string[] {
  const parsed = readConfig(repoRoot);
  if (!parsed) return [];
  const value = parsed[CAPTURE_PATTERNS_FIELD];
  if (!Array.isArray(value)) return [];
  return value.filter(
    (entry): entry is string => typeof entry === "string" && entry.length > 0,
  );
}

export interface WriteEncryptionKeyOptions {
  /** Overwrite an existing encryption_key value */
  force?: boolean;
}

/**
 * Write the encryption key to the per-repo envi config file.
 *
 * - If no config file exists, creates `envi.config.maml` with a header comment
 *   explaining what the file is for.
 * - If only the legacy `envi.maml` exists, edits it in place. Migration to the
 *   new filename is left to the user so they can commit the rename.
 * - If a config file exists and already has an `encryption_key`, refuses
 *   unless `force` is set, in which case the existing value is replaced in
 *   place (preserves surrounding content and comments).
 * - If a config file exists without an `encryption_key`, appends the field
 *   inside the top-level object, preserving the rest of the file.
 *
 * @throws Error when `force` is false and a key is already set.
 */
export function writeEncryptionKey(
  repoRoot: string,
  key: string,
  options: WriteEncryptionKeyOptions = {},
): void {
  const existing = findExistingKeyFile(repoRoot);
  const force = options.force ?? false;

  if (!existing) {
    const path = join(repoRoot, KEY_FILE_NAME);
    const lines = [
      "{",
      ...COMMENT_BLOCK.map((line) => `  ${line}`),
      `  ${ENCRYPTION_KEY_FIELD}: "${key}"`,
      "}",
      "",
    ];
    writeFileSync(path, lines.join("\n"), "utf-8");
    return;
  }

  const path = existing.path;
  const filename = existing.isLegacy ? LEGACY_KEY_FILE_NAME : KEY_FILE_NAME;
  const content = readFileSync(path, "utf-8");
  const keyLine = new RegExp(`^(\\s*)${ENCRYPTION_KEY_FIELD}:\\s*"[^"]*"`, "m");

  if (keyLine.test(content)) {
    if (!force) {
      throw new Error(
        `${ENCRYPTION_KEY_FIELD} is already set in ${filename}. Use --force to overwrite.`,
      );
    }
    const updated = content.replace(
      keyLine,
      `$1${ENCRYPTION_KEY_FIELD}: "${key}"`,
    );
    writeFileSync(path, updated, "utf-8");
    return;
  }

  /** Insert the key (with comment block) before the last closing brace */
  const lastBraceIdx = content.lastIndexOf("}");
  if (lastBraceIdx === -1) {
    throw new Error(
      `${filename} is malformed: missing closing brace. Fix the file or delete it and re-run.`,
    );
  }
  const before = content.slice(0, lastBraceIdx).replace(/\s+$/, "");
  const after = content.slice(lastBraceIdx);
  const insertion = [
    "",
    ...COMMENT_BLOCK.map((line) => `  ${line}`),
    `  ${ENCRYPTION_KEY_FIELD}: "${key}"`,
    "",
  ].join("\n");
  writeFileSync(path, `${before}\n${insertion}${after}`, "utf-8");
}

/**
 * Generate a new encryption key
 *
 * Returns 32 cryptographically random bytes encoded as base64url (~43 chars,
 * no padding). The key is opaque and used directly as the secret for
 * `encrypt()` / `decrypt()` in src/utils/encryption.ts.
 */
export function generateKey(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Test-only: clear the legacy-hint dedupe set so unit tests can re-trigger the
 * info message after mocking `existsSync`. Not exported from the package
 * barrel.
 */
export function __resetLegacyHintCache(): void {
  legacyHintShown.clear();
}
