import { parse } from "maml.js";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Per-repo envi config filename.
 *
 * No leading dot — meant to be visible and committed alongside source code.
 * Holds an optional `encryption_key` plus any future per-repo configuration.
 */
export const KEY_FILE_NAME = "envi.maml";

/** MAML key under which the encryption key is stored */
const ENCRYPTION_KEY_FIELD = "encryption_key";

const COMMENT_BLOCK = [
  "# Generated by `envi create-key`. This is a team-shared encryption key",
  "# meant to be committed — it protects envi-packed env files that travel",
  "# outside the repo (chat, email), not the repo's own contents. Anyone",
  "# with repo access can decrypt, so this repo should be private. For",
  "# public repos, skip envi.maml and let `envi pack` / `envi unpack` fall",
  "# back to manifest-based encryption instead.",
  "#",
  "# See: https://envi.codecompose.dev/commands/create-key",
];

/**
 * Get the absolute path to envi.maml in a repository
 */
export function getKeyFilePath(repoRoot: string): string {
  return join(repoRoot, KEY_FILE_NAME);
}

/**
 * Check whether the per-repo envi.maml exists.
 *
 * Note: this does not check whether `encryption_key` is set inside it; use
 * `readEncryptionKey` for that.
 */
export function hasKeyFile(repoRoot: string): boolean {
  return existsSync(getKeyFilePath(repoRoot));
}

/**
 * Read the encryption key from envi.maml if present.
 *
 * Returns null when the file is missing, can't be parsed, or has no
 * `encryption_key` field.
 */
export function readEncryptionKey(repoRoot: string): string | null {
  const path = getKeyFilePath(repoRoot);
  if (!existsSync(path)) {
    return null;
  }
  try {
    const content = readFileSync(path, "utf-8");
    const parsed = parse(content) as Record<string, unknown> | null;
    if (parsed && typeof parsed === "object") {
      const value = parsed[ENCRYPTION_KEY_FIELD];
      if (typeof value === "string" && value.length > 0) {
        return value;
      }
    }
  } catch {
    /** Treat malformed file as "no key" — caller surfaces a clearer error */
  }
  return null;
}

export interface WriteEncryptionKeyOptions {
  /** Overwrite an existing encryption_key value */
  force?: boolean;
}

/**
 * Write the encryption key to envi.maml.
 *
 * - If envi.maml does not exist, creates it with a header comment explaining
 *   what the file is for.
 * - If envi.maml exists and already has an `encryption_key`, refuses unless
 *   `force` is set, in which case the existing value is replaced in place
 *   (preserves surrounding content and comments).
 * - If envi.maml exists without an `encryption_key`, appends the field
 *   inside the top-level object, preserving the rest of the file.
 *
 * @throws Error when `force` is false and a key is already set.
 */
export function writeEncryptionKey(
  repoRoot: string,
  key: string,
  options: WriteEncryptionKeyOptions = {},
): void {
  const path = getKeyFilePath(repoRoot);
  const force = options.force ?? false;

  if (!existsSync(path)) {
    const lines = [
      "{",
      ...COMMENT_BLOCK.map((line) => `  ${line}`),
      `  ${ENCRYPTION_KEY_FIELD}: "${key}"`,
      "}",
      "",
    ];
    writeFileSync(path, lines.join("\n"), "utf-8");
    return;
  }

  const content = readFileSync(path, "utf-8");
  const keyLine = new RegExp(`^(\\s*)${ENCRYPTION_KEY_FIELD}:\\s*"[^"]*"`, "m");

  if (keyLine.test(content)) {
    if (!force) {
      throw new Error(
        `${ENCRYPTION_KEY_FIELD} is already set in ${KEY_FILE_NAME}. Use --force to overwrite.`,
      );
    }
    const updated = content.replace(
      keyLine,
      `$1${ENCRYPTION_KEY_FIELD}: "${key}"`,
    );
    writeFileSync(path, updated, "utf-8");
    return;
  }

  /** Insert the key (with comment block) before the last closing brace */
  const lastBraceIdx = content.lastIndexOf("}");
  if (lastBraceIdx === -1) {
    throw new Error(
      `${KEY_FILE_NAME} is malformed: missing closing brace. Fix the file or delete it and re-run.`,
    );
  }
  const before = content.slice(0, lastBraceIdx).replace(/\s+$/, "");
  const after = content.slice(lastBraceIdx);
  const insertion = [
    "",
    ...COMMENT_BLOCK.map((line) => `  ${line}`),
    `  ${ENCRYPTION_KEY_FIELD}: "${key}"`,
    "",
  ].join("\n");
  writeFileSync(path, `${before}\n${insertion}${after}`, "utf-8");
}

/**
 * Generate a new encryption key
 *
 * Returns 32 cryptographically random bytes encoded as base64url (~43 chars,
 * no padding). The key is opaque and used directly as the secret for
 * `encrypt()` / `decrypt()` in src/utils/encryption.ts.
 */
export function generateKey(): string {
  return randomBytes(32).toString("base64url");
}
