import { parse } from "maml.js";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  KEY_FILE_NAME,
  generateKey,
  getKeyFilePath,
  hasKeyFile,
  readEncryptionKey,
  writeEncryptionKey,
} from "./key-file";

vi.mock("node:fs");

describe("key-file", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe("KEY_FILE_NAME", () => {
    it("is envi.maml (no leading dot — meant to be visible/committed)", () => {
      expect(KEY_FILE_NAME).toBe("envi.maml");
      expect(KEY_FILE_NAME.startsWith(".")).toBe(false);
    });
  });

  describe("getKeyFilePath", () => {
    it("joins repo root with the key filename", () => {
      expect(getKeyFilePath("/repo")).toBe("/repo/envi.maml");
    });
  });

  describe("hasKeyFile", () => {
    it("delegates to existsSync", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      expect(hasKeyFile("/repo")).toBe(true);
      vi.mocked(existsSync).mockReturnValue(false);
      expect(hasKeyFile("/repo")).toBe(false);
    });
  });

  describe("readEncryptionKey", () => {
    it("returns null when envi.maml is missing", () => {
      vi.mocked(existsSync).mockReturnValue(false);
      expect(readEncryptionKey("/repo")).toBeNull();
    });

    it("returns the encryption_key field when present", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue(
        '{\n  encryption_key: "thekey"\n}',
      );
      expect(readEncryptionKey("/repo")).toBe("thekey");
    });

    it("returns null when encryption_key is missing from the config", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue('{\n  other: "x"\n}');
      expect(readEncryptionKey("/repo")).toBeNull();
    });

    it("returns null when the file is malformed", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue("garbage that won't parse");
      expect(readEncryptionKey("/repo")).toBeNull();
    });

    it("returns null when encryption_key is empty", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue('{\n  encryption_key: ""\n}');
      expect(readEncryptionKey("/repo")).toBeNull();
    });
  });

  describe("writeEncryptionKey", () => {
    it("creates a new file with a header comment when missing", () => {
      vi.mocked(existsSync).mockReturnValue(false);
      writeEncryptionKey("/repo", "newkey");

      expect(writeFileSync).toHaveBeenCalledOnce();
      const [path, content] = vi.mocked(writeFileSync).mock.calls[0]!;
      expect(path).toBe("/repo/envi.maml");
      expect(typeof content).toBe("string");
      expect(content as string).toContain('encryption_key: "newkey"');
      expect(content as string).toContain("# Generated by `envi create-key`");
      expect(content as string).toContain(
        "envi.codecompose.dev/commands/create-key",
      );
      expect(content as string).toContain("should be private");

      // Round-trip parse to ensure the generated MAML is valid
      const parsed = parse(content as string) as Record<string, string>;
      expect(parsed.encryption_key).toBe("newkey");
    });

    it("refuses to overwrite an existing encryption_key without force", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue(
        '{\n  encryption_key: "oldkey"\n}',
      );

      expect(() => writeEncryptionKey("/repo", "newkey")).toThrow(
        /already set/,
      );
      expect(writeFileSync).not.toHaveBeenCalled();
    });

    it("overwrites the existing key when force is true (preserves comments)", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue(
        '{\n  # user comment\n  encryption_key: "oldkey"\n  other: "preserved"\n}\n',
      );

      writeEncryptionKey("/repo", "newkey", { force: true });

      const [, content] = vi.mocked(writeFileSync).mock.calls[0]!;
      expect(content as string).toContain('encryption_key: "newkey"');
      expect(content as string).not.toContain("oldkey");
      expect(content as string).toContain("# user comment");
      expect(content as string).toContain('other: "preserved"');
    });

    it("inserts the key into an existing config that has no encryption_key", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue(
        '{\n  some_other_field: "x"\n}\n',
      );

      writeEncryptionKey("/repo", "newkey");

      const [, content] = vi.mocked(writeFileSync).mock.calls[0]!;
      expect(content as string).toContain('encryption_key: "newkey"');
      expect(content as string).toContain('some_other_field: "x"');

      // Parses cleanly with both fields
      const parsed = parse(content as string) as Record<string, string>;
      expect(parsed.encryption_key).toBe("newkey");
      expect(parsed.some_other_field).toBe("x");
    });

    it("throws when an existing file has no closing brace", () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue("not a valid maml object");

      expect(() => writeEncryptionKey("/repo", "newkey")).toThrow(/malformed/);
    });
  });

  describe("generateKey", () => {
    it("returns a non-empty base64url string", () => {
      const key = generateKey();
      expect(key.length).toBeGreaterThan(0);
      expect(key).toMatch(/^[A-Za-z0-9_-]+$/);
    });

    it("produces unique values on repeated calls", () => {
      expect(generateKey()).not.toBe(generateKey());
    });
  });
});
